#!/bin/bash

# List of URLs to pick from
URL_LIST=(
    "http://grafana:3000/d/tor-jenkins-status/tor-jenkins-status?orgId=1\&refresh=15m\&kiosk"
    "https://docs.toradex.com/107154-toradex-logo.svg"
)

# Choose a random URL
RANDOM=$$$(</dev/urandom tr -dc 0-9 | dd bs=5 count=1 2>/dev/null)
URL=${URL_LIST[ $RANDOM % ${#URL_LIST[@]} ]}
echo "$URL"
