version: "3.9"
services:

  data-acquisition:
    image: ${DOCKER_LOGIN}/torizon-os-build-status-data-acquisition:${TAG}
    networks:
      - influxdbnet
      - frontend
    command: ["influxdb", "8086"]
    depends_on:
      - influxdb
    #environment:
    #  - DEBUG=INFO # set this variable to a valid value for debugging
    #  - DEMO=1 # set this variable to any value for generating random data points
    restart: on-failure

  influxdb:
    image: ${DOCKER_LOGIN}/torizon-os-build-status-influxdb:${TAG}
    networks:
      - influxdbnet
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=torizon
      - DOCKER_INFLUXDB_INIT_PASSWORD=T0rizonEasy2Us&
      - DOCKER_INFLUXDB_INIT_ORG=toradex
      - DOCKER_INFLUXDB_INIT_BUCKET=jenkinsdatabucket
      - DOCKER_INFLUXDB_INIT_RETENTION=60m
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=T0rizonTh3Ea&IndustrialPlatform
      - INFLUXD_LOG_LEVEL=error
    volumes:
      - "influxdb-volume:/var/lib/influxdb2"
    restart: on-failure

  grafana:
    image: ${DOCKER_LOGIN}/torizon-os-build-status-grafana:${TAG}
    networks:
      - influxdbnet
      - frontend
    volumes:
      - "grafana-storage:/var/lib/grafana"
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
      - data-acquisition
    restart: on-failure

  weston:
    image: ${DOCKER_LOGIN}/torizon-os-build-status-weston:${TAG}
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for /dev/tty devices
      - 'c 4:* rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
    restart: on-failure

  browser:
    image: ${DOCKER_LOGIN}/torizon-os-build-status-browser:${TAG}
    environment:
      - MACHINE
      #- RESTART_INTERVAL=1800 # set to override default
    security_opt:
      - seccomp:unconfined
    networks:
      - frontend
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
      - type: bind
        source: /home/torizon/.config/tdx_br_photo
        target: /tdx_br_photo
    depends_on:
      - weston
      - grafana
      - influxdb
      - data-acquisition
    shm_size: '256mb'
    device_cgroup_rules:
      # ... for /dev/dri devices
      - 'c 226:* rmw'
    restart: always

networks:
  influxdbnet:
    internal: true
  frontend:
    internal: false

volumes:
  grafana-storage:
  influxdb-storage: