services:
  torizon-os-build-status-data-acquisition:
    platform: linux/arm64
    environment:
    - DEBUG=1
    - DEMO=1
    networks:
    - influxdbnet
    - frontend
    command:
    - influxdb
    - "8086"
    depends_on:
    - influxdb
    image: leograba/torizon-os-build-status-data-acquisition:rc
  influxdb:
    image: leograba/torizon-os-build-status-influxdb:0.3.0
    platform: linux/arm64
    networks:
    - influxdbnet
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=torizon
    - DOCKER_INFLUXDB_INIT_PASSWORD=T0rizonEasy2Us&
    - DOCKER_INFLUXDB_INIT_ORG=toradex
    - DOCKER_INFLUXDB_INIT_BUCKET=jenkinsdatabucket
    - DOCKER_INFLUXDB_INIT_RETENTION=60m
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=T0rizonTh3Ea&IndustrialPlatform
    - INFLUXD_LOG_LEVEL=error
  grafana:
    platform: linux/arm64
    ports:
    - 3000:3000
    networks:
    - influxdbnet
    - frontend
    image: leograba/torizon-os-build-status-grafana:0.3.0
    depends_on:
    - influxdb
    - torizon-os-build-status-data-acquisition
    volumes:
    - $PWD/debug/grafana-config/grafana.ini:/etc/grafana/grafana.ini
    - $PWD/debug/grafana-config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    - $PWD/debug/grafana-config/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    - $PWD/debug/grafana-config/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
networks:
  frontend:
    internal: false
  influxdbnet:
    internal: true
version: "3.9"
