name: Docker Build and Push
description: Reusable Docker build and push logic

inputs:
  username:
    description: 'Docker Hub registry username'
    required: true
  password:
    description: 'Docker Hub password'
    required: true
  context:
    description: 'The Docker build context'
    required: true
  imgarch:
    description: 'Architecture of the container image'
    required: true
  tagname:
    description: 'Docker tag name before the :'
    required: true
  tagversion:
    description: 'Docker tag version after the :'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ${{ inputs.context }}
        platforms: linux/${{ inputs.imgarch }}
        build-args: |
          IMAGE_ARCH=${{ inputs.imgarch }}
        tags: |
          ${{ inputs.username }}/${{ inputs.tagname }}:${{ inputs.tagversion }}
