ARG INFLUXDB_VERSION=2.7.6

##
# Board architecture
# arm or arm64
##
ARG IMAGE_ARCH=

# DEPLOY ------------------------------------------------------------------------
FROM --platform=linux/${IMAGE_ARCH} influxdb:${INFLUXDB_VERSION}-alpine
