name: Weston

env:
  wdir: weston
  arch: arm
  imgname: torizon-os-build-status-weston

on:
  push:
    paths:
      - 'weston/**'
  release:
    types: [created]

jobs:
  build-weston:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.wdir }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Build and push release candidate
        uses: ./.github/actions/docker-build-push
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: ${{ env.wdir }}
          imgarch: ${{ env.arch }}
          tagname: ${{ env.imgname }}
          tagversion: rc

  release-weston:
    needs: [build-weston]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.wdir }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Get container tag
        run: |
          echo "CONTAINER_TAG=$(jq -r '.docker_tag' .vscode/settings.json)" >> $GITHUB_ENV

      - name: Build and push tagged release
        uses: ./.github/actions/docker-build-push
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: ${{ env.wdir }}
          imgarch: ${{ env.arch }}
          tagname: ${{ env.imgname }}
          tagversion: ${{ env.CONTAINER_TAG }}
